### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590) 

### ISSUE THREAD

**Issue by zonito** [apigee/api-platform-samples#88]
From last Friday till today, we have been facing an issue in the deployments of proxies. Sometimes it works but most of the time we see SSL error (attached code below). 

```
Writing ../build/test/testcase-update-user-attributes-by-region.sh to test/testcase-update-user-attributes-by-region.sh 
Writing ../build/test/testcase-update-user-attributes.sh to test/testcase-update-user-attributes.sh 
Traceback (most recent call last): 
File "deploy.py", line 204, in <module> 
resp = httpCall('POST', uri, hdrs, body) 
File "deploy.py", line 29, in httpCall 
conn.request(verb, uri, body, hdrs) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request 
self._send_request(method, url, body, headers) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request 
self.endheaders(body) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders 
self._send_output(message_body) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output 
self.send(msg) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send 
self.connect() 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1274, in connect 
server_hostname=server_hostname) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket 
_context=self) 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__ 
self.do_handshake() 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake 
self._sslobj.do_handshake() 
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590) 
If 'State: deployed', then your API Proxy is ready to be invoked. 
```

Many of our colleagues are facing this issue, we tried using mac os and linux OS. 

Please have a look urgently, as we are unable to deploy proxy on time.

**Comment by WWitman** [comment]
It's possible the python script used to deploy the samples does not work in some cases from behind corporate firewalls. See this post in the Apigee Community: https://community.apigee.com/questions/47912/ssl-certificate-verify-failed-error.html

An option is to use the apigeetool utility to deploy your proxies: https://www.npmjs.com/package/apigeetool
